### ISSUE TITLE
ArgumentError (wrong number of arguments (given 2, expected 0))

### ISSUE THREAD

**Issue by OrrYakobi** [hggeorgiev/rails-jwt-auth-tutorial#4]
I followed the guide and implemented everything as the guide did.

I get this error:

```
ArgumentError (wrong number of arguments (given 2, expected 0)):
  
app/controllers/authentication_controller.rb:5:in `authenticate'
```

When I call:
```
$ curl -H "Content-Type: application/json" -X POST -d '{"email":"example@mail.com","password":"123"}' http://localhost:3000/authenticate
```

**Comment by edwincarbajal** [comment]
@OrrYakobi Hey did you figure out how to get around this issue?

**Comment by madhusudhan1234** [comment]
And I got this error.

```
{"status":500,"error":"Internal Server Error","exception":"#\u003cTypeError: no implicit conversion of nil into String\u003e","traces":{"Application Trace":[{"id":8,"trace":"lib/json_web_token.rb:5:in `encode'"},{"id":9,"trace":"app/commands/authenticate_user.rb:10:in `call'"},{"id":12,"trace":"app/controllers/authentication_controller.rb:5:in `authenticate'"}],"Framework Trace":[{"id":0,"trace":"jwt (2.1.0) lib/jwt/algos/hmac.rb:14:in `digest'"},{"id":1,"trace":"jwt (2.1.0) lib/jwt/algos/hmac.rb:14:in `sign'"},{"id":2,"trace":"jwt (2.1.0) lib/jwt/signature.rb:35:in `sign'"},{"id":3,"trace":"jwt (2.1.0) lib/jwt/encode.rb:39:in `encoded_signature'"},{"id":4,"trace":"jwt (2.1.0) lib/jwt/encode.rb:47:in `encode_segments'"},{"id":5,"trace":"jwt (2.1.0) lib/jwt/encode.rb:20:in `initialize'"},{"id":6,"trace":"jwt (2.1.0) lib/jwt.rb:21:in `new'"},{"id":7,"trace":"jwt (2.1.0) lib/jwt.rb:21:in `encode'"},{"id":10,"trace":"simple_command (0.0.9) lib/simple_command.rb:21:in `call'"},{"id":11,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `call'"},{"id":13,"trace":"actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"},{"id":14,"trace":"actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'"},{"id":15,"trace":"actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":16,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'"},{"id":17,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'"},{"id":18,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'"},{"id":19,"trace":"actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"},{"id":20,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'"},{"id":21,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'"},{"id":22,"trace":"activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'"},{"id":23,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'"},{"id":24,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"},{"id":25,"trace":"actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'"},{"id":26,"trace":"activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'"},{"id":27,"trace":"actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'"},{"id":28,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'"},{"id":29,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'"},{"id":30,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'"},{"id":31,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'"},{"id":32,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'"},{"id":33,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'"},{"id":34,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'"},{"id":35,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'"},{"id":36,"trace":"rack (2.0.5) lib/rack/etag.rb:25:in `call'"},{"id":37,"trace":"rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'"},{"id":38,"trace":"rack (2.0.5) lib/rack/head.rb:12:in `call'"},{"id":39,"trace":"activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'"},{"id":40,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'"},{"id":41,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'"},{"id":42,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"},{"id":43,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":44,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'"},{"id":45,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"id":46,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'"},{"id":47,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'"},{"id":48,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'"},{"id":49,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'"},{"id":50,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'"},{"id":51,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'"},{"id":52,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"id":53,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'"},{"id":54,"trace":"rack (2.0.5) lib/rack/runtime.rb:22:in `call'"},{"id":55,"trace":"activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"id":56,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":57,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'"},{"id":58,"trace":"rack (2.0.5) lib/rack/sendfile.rb:111:in `call'"},{"id":59,"trace":"railties (5.2.1) lib/rails/engine.rb:524:in `call'"},{"id":60,"trace":"puma (3.12.0) lib/puma/configuration.rb:225:in `call'"},{"id":61,"trace":"puma (3.12.0) lib/puma/server.rb:658:in `handle_request'"},{"id":62,"trace":"puma (3.12.0) lib/puma/server.rb:472:in `process_client'"},{"id":63,"trace":"puma (3.12.0) lib/puma/server.rb:332:in `block in run'"},{"id":64,"trace":"puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'"}],"Full Trace":[{"id":0,"trace":"jwt (2.1.0) lib/jwt/algos/hmac.rb:14:in `digest'"},{"id":1,"trace":"jwt (2.1.0) lib/jwt/algos/hmac.rb:14:in `sign'"},{"id":2,"trace":"jwt (2.1.0) lib/jwt/signature.rb:35:in `sign'"},{"id":3,"trace":"jwt (2.1.0) lib/jwt/encode.rb:39:in `encoded_signature'"},{"id":4,"trace":"jwt (2.1.0) lib/jwt/encode.rb:47:in `encode_segments'"},{"id":5,"trace":"jwt (2.1.0) lib/jwt/encode.rb:20:in `initialize'"},{"id":6,"trace":"jwt (2.1.0) lib/jwt.rb:21:in `new'"},{"id":7,"trace":"jwt (2.1.0) lib/jwt.rb:21:in `encode'"},{"id":8,"trace":"lib/json_web_token.rb:5:in `encode'"},{"id":9,"trace":"app/commands/authenticate_user.rb:10:in `call'"},{"id":10,"trace":"simple_command (0.0.9) lib/simple_command.rb:21:in `call'"},{"id":11,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `call'"},{"id":12,"trace":"app/controllers/authentication_controller.rb:5:in `authenticate'"},{"id":13,"trace":"actionpack (5.2.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"},{"id":14,"trace":"actionpack (5.2.1) lib/abstract_controller/base.rb:194:in `process_action'"},{"id":15,"trace":"actionpack (5.2.1) lib/action_controller/metal/rendering.rb:30:in `process_action'"},{"id":16,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'"},{"id":17,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'"},{"id":18,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'"},{"id":19,"trace":"actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"},{"id":20,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'"},{"id":21,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'"},{"id":22,"trace":"activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'"},{"id":23,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'"},{"id":24,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"},{"id":25,"trace":"actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'"},{"id":26,"trace":"activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'"},{"id":27,"trace":"actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'"},{"id":28,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'"},{"id":29,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'"},{"id":30,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'"},{"id":31,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'"},{"id":32,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'"},{"id":33,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'"},{"id":34,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'"},{"id":35,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'"},{"id":36,"trace":"rack (2.0.5) lib/rack/etag.rb:25:in `call'"},{"id":37,"trace":"rack (2.0.5) lib/rack/conditional_get.rb:38:in `call'"},{"id":38,"trace":"rack (2.0.5) lib/rack/head.rb:12:in `call'"},{"id":39,"trace":"activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'"},{"id":40,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'"},{"id":41,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'"},{"id":42,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"},{"id":43,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":44,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'"},{"id":45,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"id":46,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'"},{"id":47,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'"},{"id":48,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'"},{"id":49,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'"},{"id":50,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'"},{"id":51,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'"},{"id":52,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"id":53,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'"},{"id":54,"trace":"rack (2.0.5) lib/rack/runtime.rb:22:in `call'"},{"id":55,"trace":"activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"id":56,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":57,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'"},{"id":58,"trace":"rack (2.0.5) lib/rack/sendfile.rb:111:in `call'"},{"id":59,"trace":"railties (5.2.1) lib/rails/engine.rb:524:in `call'"},{"id":60,"trace":"puma (3.12.0) lib/puma/configuration.rb:225:in `call'"},{"id":61,"trace":"puma (3.12.0) lib/puma/server.rb:658:in `handle_request'"},{"id":62,"trace":"puma (3.12.0) lib/puma/server.rb:472:in `process_client'"},{"id":63,"trace":"puma (3.12.0) lib/puma/server.rb:332:in `block in run'"},{"id":64,"trace":"puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'"}]}}%   
```

**Comment by madhusudhan1234** [comment]
Even after fixing the issue I got a new error while calling ```http://localhost:3000/items```

```
{"status":500,"error":"Internal Server Error","exception":"#\u003cArgumentError: wrong number of arguments (given 1, expected 0)\u003e","traces":{"Application Trace":[{"id":3,"trace":"app/controllers/application_controller.rb:8:in `authenticate_request'"}],"Framework Trace":[{"id":0,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `initialize'"},{"id":1,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `new'"},{"id":2,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `call'"},{"id":4,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:426:in `block in make_lambda'"},{"id":5,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'"},{"id":6,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in \u003cmodule:Callbacks\u003e'"},{"id":7,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:199:in `block in halting'"},{"id":8,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'"},{"id":9,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `each'"},{"id":10,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `invoke_before'"},{"id":11,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:131:in `run_callbacks'"},{"id":12,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'"},{"id":13,"trace":"actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"},{"id":14,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'"},{"id":15,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'"},{"id":16,"trace":"activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'"},{"id":17,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'"},{"id":18,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"},{"id":19,"trace":"actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'"},{"id":20,"trace":"activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'"},{"id":21,"trace":"actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'"},{"id":22,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'"},{"id":23,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'"},{"id":24,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'"},{"id":25,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'"},{"id":26,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'"},{"id":27,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'"},{"id":28,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'"},{"id":29,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'"},{"id":30,"trace":"rack (2.0.5) lib/rack/etag.rb:25:in `call'"},{"id":31,"trace":"rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'"},{"id":32,"trace":"rack (2.0.5) lib/rack/head.rb:12:in `call'"},{"id":33,"trace":"activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'"},{"id":34,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'"},{"id":35,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'"},{"id":36,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"},{"id":37,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":38,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'"},{"id":39,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"id":40,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'"},{"id":41,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'"},{"id":42,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'"},{"id":43,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'"},{"id":44,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'"},{"id":45,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'"},{"id":46,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"id":47,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'"},{"id":48,"trace":"rack (2.0.5) lib/rack/runtime.rb:22:in `call'"},{"id":49,"trace":"activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"id":50,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":51,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'"},{"id":52,"trace":"rack (2.0.5) lib/rack/sendfile.rb:111:in `call'"},{"id":53,"trace":"railties (5.2.1) lib/rails/engine.rb:524:in `call'"},{"id":54,"trace":"puma (3.12.0) lib/puma/configuration.rb:225:in `call'"},{"id":55,"trace":"puma (3.12.0) lib/puma/server.rb:658:in `handle_request'"},{"id":56,"trace":"puma (3.12.0) lib/puma/server.rb:472:in `process_client'"},{"id":57,"trace":"puma (3.12.0) lib/puma/server.rb:332:in `block in run'"},{"id":58,"trace":"puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'"}],"Full Trace":[{"id":0,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `initialize'"},{"id":1,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `new'"},{"id":2,"trace":"simple_command (0.0.9) lib/simple_command.rb:9:in `call'"},{"id":3,"trace":"app/controllers/application_controller.rb:8:in `authenticate_request'"},{"id":4,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:426:in `block in make_lambda'"},{"id":5,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'"},{"id":6,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in \u003cmodule:Callbacks\u003e'"},{"id":7,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:199:in `block in halting'"},{"id":8,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `block in invoke_before'"},{"id":9,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `each'"},{"id":10,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:513:in `invoke_before'"},{"id":11,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:131:in `run_callbacks'"},{"id":12,"trace":"actionpack (5.2.1) lib/abstract_controller/callbacks.rb:41:in `process_action'"},{"id":13,"trace":"actionpack (5.2.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"},{"id":14,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'"},{"id":15,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `block in instrument'"},{"id":16,"trace":"activesupport (5.2.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'"},{"id":17,"trace":"activesupport (5.2.1) lib/active_support/notifications.rb:168:in `instrument'"},{"id":18,"trace":"actionpack (5.2.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'"},{"id":19,"trace":"actionpack (5.2.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'"},{"id":20,"trace":"activerecord (5.2.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'"},{"id":21,"trace":"actionpack (5.2.1) lib/abstract_controller/base.rb:134:in `process'"},{"id":22,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:191:in `dispatch'"},{"id":23,"trace":"actionpack (5.2.1) lib/action_controller/metal.rb:252:in `dispatch'"},{"id":24,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'"},{"id":25,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'"},{"id":26,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'"},{"id":27,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `each'"},{"id":28,"trace":"actionpack (5.2.1) lib/action_dispatch/journey/router.rb:35:in `serve'"},{"id":29,"trace":"actionpack (5.2.1) lib/action_dispatch/routing/route_set.rb:840:in `call'"},{"id":30,"trace":"rack (2.0.5) lib/rack/etag.rb:25:in `call'"},{"id":31,"trace":"rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'"},{"id":32,"trace":"rack (2.0.5) lib/rack/head.rb:12:in `call'"},{"id":33,"trace":"activerecord (5.2.1) lib/active_record/migration.rb:559:in `call'"},{"id":34,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'"},{"id":35,"trace":"activesupport (5.2.1) lib/active_support/callbacks.rb:98:in `run_callbacks'"},{"id":36,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"},{"id":37,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":38,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'"},{"id":39,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'"},{"id":40,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:38:in `call_app'"},{"id":41,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `block in call'"},{"id":42,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'"},{"id":43,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:28:in `tagged'"},{"id":44,"trace":"activesupport (5.2.1) lib/active_support/tagged_logging.rb:71:in `tagged'"},{"id":45,"trace":"railties (5.2.1) lib/rails/rack/logger.rb:26:in `call'"},{"id":46,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'"},{"id":47,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'"},{"id":48,"trace":"rack (2.0.5) lib/rack/runtime.rb:22:in `call'"},{"id":49,"trace":"activesupport (5.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"},{"id":50,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"},{"id":51,"trace":"actionpack (5.2.1) lib/action_dispatch/middleware/static.rb:127:in `call'"},{"id":52,"trace":"rack (2.0.5) lib/rack/sendfile.rb:111:in `call'"},{"id":53,"trace":"railties (5.2.1) lib/rails/engine.rb:524:in `call'"},{"id":54,"trace":"puma (3.12.0) lib/puma/configuration.rb:225:in `call'"},{"id":55,"trace":"puma (3.12.0) lib/puma/server.rb:658:in `handle_request'"},{"id":56,"trace":"puma (3.12.0) lib/puma/server.rb:472:in `process_client'"},{"id":57,"trace":"puma (3.12.0) lib/puma/server.rb:332:in `block in run'"},{"id":58,"trace":"puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'"}]}}%  
```

**Comment by hggeorgiev** [comment]
Hello @OrrYakobi ,
This is because the tutorial is outdated and you've probably installed newer versions of them. If you'd like to update the tutorial and its dependencies, feel free to open a PR.
